USE medipulse_ai;
SHOW TABLES;
SELECT COUNT(*) FROM patients;
SELECT DATABASE();
SHOW DATABASES;
USE medipulse_ai;
SELECT DATABASE();
SHOW TABLES;
SELECT COUNT(*) FROM appointments;
SELECT COUNT(*) FROM patients;
SHOW CREATE TABLE patients;
USE medipulse_ai;
SELECT COUNT(*) FROM medipulse_ai.patients;
SHOW TABLES;
DESCRIBE patients;
SELECT COUNT(*) FROM doctors;
SELECT COUNT(*) AS patients FROM patients;
SELECT COUNT(*) AS doctors FROM doctors;
SELECT COUNT(*) AS appointments FROM appointments;
SELECT COUNT(*) AS treatments FROM treatments;
SELECT COUNT(*) AS billing FROM billing;